// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/NCUHOME-Y/25-Hack4-Unimate-BE/app/social/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/countranking",
				Handler: GetUserCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dakaRanking",
				Handler: GetUserTotalDakaHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getAllPosts",
				Handler: GetAllPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUseflagrRank",
				Handler: GetUserByFlagNumberHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getflag",
				Handler: GetVisibleFlagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/learnTimeRanking",
				Handler: GetUserMonthLearnTimeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat/history/:room_id",
				Handler: GetChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chat/rooms",
				Handler: GetChatRoomsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat/rooms",
				Handler: CreateChatRoomHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/chat/rooms/:room_id",
				Handler: DeleteChatRoomHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/commentOnPost",
				Handler: CommentOnPostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/deleteComment",
				Handler: DeleteUserPostCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/deleteUserPost",
				Handler: DeleteUserPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/flagcomment",
				Handler: CommentOnFlagHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/flagdeletecomment",
				Handler: DeleteFlagCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUserLikedPosts",
				Handler: GetUserLikedPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getflaglike",
				Handler: GetFlagLikesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getpostlike",
				Handler: GetPostLikesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/likeFlag",
				Handler: LikeFlagHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/likepost",
				Handler: LikePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/postUserPost",
				Handler: PostUserPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/private-chat/conversations",
				Handler: GetPrivateConversationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/private-chat/history",
				Handler: GetPrivateChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/searchPosts",
				Handler: SearchPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ws/chat",
				Handler: WsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
