// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/NCUHOME-Y/25-Hack4-Unimate-BE/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/forgetcode",
				Handler: ForgetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/loginWithOTP",
				Handler: LoginWithOTPHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendEmailCode",
				Handler: SendEmailCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verifyEmail",
				Handler: VerifyEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/UpdateStatus",
				Handler: UpdateStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/addPoints",
				Handler: AddPointsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getTodayPoints",
				Handler: GetTodayPointsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUser",
				Handler: GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUserAchievement",
				Handler: GetUserAchievementHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUserStats",
				Handler: GetUserStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/searchUser",
				Handler: SearchUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/swithhead",
				Handler: SwitchHeadHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/updatePassword",
				Handler: UpdatePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/updateRemindStatus",
				Handler: UpdateRemindStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/updateRemindTime",
				Handler: UpdateRemindTimeHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/updateUsername",
				Handler: UpdateUsernameHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
