// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddFlagReq struct {
	Title       string `json:"title"`
	Detail      string `json:"detail"`
	IsPublic    bool   `json:"is_public"`
	Label       int    `json:"label"`
	Priority    int    `json:"priority"`
	Total       int    `json:"total"`
	Points      int    `json:"points"`
	DailyLimit  int    `json:"daily_limit"`
	IsRecurring bool   `json:"is_recurring"`
	StartTime   string `json:"start_time"`
	EndTime     string `json:"end_time"`
}

type AddFlagResp struct {
	Success bool     `json:"success"`
	Message string   `json:"message"`
	Flag    FlagItem `json:"flag"`
}

type AddLearnTimeReq struct {
	Duration int `json:"duration"` // 分钟
}

type DakaRecord struct {
	Date string `json:"date"`
}

type DeleteFlagReq struct {
	Id uint `json:"id"`
}

type DoneFlagReq struct {
	Id uint `json:"id"`
}

type DoneFlagResp struct {
	Success   bool `json:"success"`
	Count     int  `json:"count"`
	Completed bool `json:"completed"`
}

type FinishDoneFlagReq struct {
	Id uint `json:"id"`
}

type FlagItem struct {
	Id        uint   `json:"id"`
	Title     string `json:"title"`
	Detail    string `json:"detail"`
	Label     int    `json:"label"`
	Priority  int    `json:"priority"`
	UserId    uint   `json:"user_id"`
	IsPublic  bool   `json:"is_public"`
	Completed bool   `json:"completed"`
	Count     int    `json:"count"`
	Total     int    `json:"total"`
	Points    int    `json:"points"`
	Likes     int    `json:"likes"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type GeneratePlanReq struct {
	Goal        string `json:"goal"`
	Days        int    `json:"days"`
	DailyHours  int    `json:"daily_hours"`
	Preferences string `json:"preferences"`
}

type GeneratePlanResp struct {
	Plan string `json:"plan"`
}

type GetDakaRecordsResp struct {
	Records []DakaRecord `json:"records"` // 实际上是数组，这里简化定义
}

type GetLabelResp struct {
	Life  int `json:"life"`
	Study int `json:"study"`
	Work  int `json:"work"`
	Like  int `json:"like"`
	Sport int `json:"sport"`
}

type GetLearnTimeResp struct {
	Records []LearnTimeRecord `json:"records"`
}

type GetRecentDoFlagUsersResp struct {
	Users []RecentDoFlagUser `json:"users"`
}

type GetUserFlagsResp struct {
	Flags []FlagItem `json:"flags"`
}

type LearnTimeRecord struct {
	Date     string `json:"date"`
	Duration int    `json:"duration"`
}

type RecentDoFlagUser struct {
	UserId   uint   `json:"user_id"`
	Name     string `json:"name"`
	HeadShow int    `json:"head_show"`
	FlagName string `json:"flag_name"`
	Time     string `json:"time"`
}

type TodayLearnTimeResp struct {
	Duration int `json:"duration"`
}

type UpdateFlagHideReq struct {
	Id uint `json:"id"`
}

type UpdateFlagReq struct {
	Id        uint   `json:"id"`
	Title     string `json:"title"`
	Detail    string `json:"detail"`
	Label     int    `json:"label"`
	Priority  int    `json:"priority"`
	Total     int    `json:"total"`
	IsPublic  bool   `json:"is_public"`
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}
