// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/NCUHOME-Y/25-Hack4-Unimate-BE/app/goal/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getRecentDoFlagUsers",
				Handler: GetRecentDoFlagUsersHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addFlag",
				Handler: AddFlagHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addLearnTime",
				Handler: AddLearnTimeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ai/generate-plan",
				Handler: GenerateLearningPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/deleteFlag",
				Handler: DeleteFlagHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/doneFlag",
				Handler: DoneFlagHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/finshDoneFlag",
				Handler: FinishDoneFlagHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/flags/expired",
				Handler: GetExpiredFlagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/flags/preset",
				Handler: GetPresetFlagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/flags/with-dates",
				Handler: GetFlagsWithDatesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get7daylearntime",
				Handler: Get7DayLearnTimeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getCurrentMonthLearnTime",
				Handler: GetCurrentMonthLearnTimeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getDakaRecords",
				Handler: GetDakaRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getDoneFlags",
				Handler: GetDoneFlagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getLearnTime180days",
				Handler: GetLearnTime180DaysHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getLearnTimemonly",
				Handler: GetLearnTimeMonthlyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getLearnTimemonth",
				Handler: GetLearnTimeMonthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getRecent6MonthsLearnTime",
				Handler: GetRecent6MonthsLearnTimeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getTodayLearnTime",
				Handler: GetTodayLearnTimeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUnDoneFlags",
				Handler: GetUnDoneFlagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUserFlags",
				Handler: GetUserFlagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getdakatotal",
				Handler: GetDakaTotalHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getlabel",
				Handler: GetLabelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getmonthdaka",
				Handler: GetMonthDakaHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/updateDaka",
				Handler: UpdateDakaHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/updateFlag",
				Handler: UpdateFlagHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/updateFlagHide",
				Handler: UpdateFlagHideHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
