// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChatMessage struct {
	Id         uint   `json:"id"`
	FromUserId uint   `json:"from"`
	ToUserId   uint   `json:"to"`
	RoomId     string `json:"room_id"`
	Content    string `json:"content"`
	CreatedAt  string `json:"created_at"`
	UserName   string `json:"user_name"`
	UserAvatar string `json:"user_avatar"`
}

type ChatRoom struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type CommentItem struct {
	Id         uint   `json:"id"`
	PostId     uint   `json:"post_id"`
	UserId     uint   `json:"userId"`
	UserName   string `json:"userName"`
	UserAvatar string `json:"userAvatar"`
	Content    string `json:"content"`
	CreatedAt  string `json:"created_at"`
}

type CommentOnFlagReq struct {
	FlagId  uint   `json:"flag_id"`
	Content string `json:"content"`
}

type CommentOnPostReq struct {
	PostId  uint   `json:"post_id"`
	Content string `json:"content"`
}

type CreateChatRoomReq struct {
	Name string `json:"name"`
}

type DeleteChatRoomReq struct {
	RoomId string `path:"room_id"`
}

type DeleteCommentReq struct {
	CommentId uint `json:"comment_id"`
}

type DeleteFlagCommentReq struct {
	CommentId uint `json:"comment_id"`
}

type DeleteUserPostReq struct {
	Id uint `json:"id"`
}

type GetAllPostsResp struct {
	Posts []PostItem `json:"posts"`
}

type GetChatHistoryResp struct {
	Messages []ChatMessage `json:"messages"`
}

type LikeFlagReq struct {
	FlagId uint `json:"flag_id"`
}

type LikePostReq struct {
	PostId uint `json:"post_id"`
}

type PostItem struct {
	Id         uint          `json:"id"`
	Title      string        `json:"title"`
	Content    string        `json:"content"`
	Like       int           `json:"like"`
	UserId     uint          `json:"user_id"`
	UserName   string        `json:"userName"`
	UserAvatar string        `json:"userAvatar"`
	CreatedAt  string        `json:"created_at"`
	Comments   []CommentItem `json:"comments"`
}

type PostUserPostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	FlagId  uint   `json:"flag_id,optional"`
}

type RankingItem struct {
	UserId   uint   `json:"user_id"`
	Name     string `json:"name"`
	HeadShow int    `json:"head_show"`
	Value    int    `json:"value"` // 可能是flag数、积分、时长等
}

type RankingResp struct {
	List []RankingItem `json:"list"`
}

type SearchPostsReq struct {
	Keyword string `json:"keyword"`
}
