// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AchievementItem struct {
	Id          uint   `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	HadDone     bool   `json:"had_done"`
	GotTime     string `json:"got_time"`
}

type AddPointsReq struct {
	Points int `json:"points"`
}

type AddPointsResp struct {
	Message string `json:"message"`
	Count   int    `json:"count"`
}

type ForgetPasswordReq struct {
	Email       string `json:"email"`
	Code        string `json:"code"`
	NewPassword string `json:"new_password"`
}

type GetUserAchievementResp struct {
	Achievements []AchievementItem `json:"achievements"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Message        string `json:"message"`
	UserId         uint   `json:"user_id"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	HeadShow       int    `json:"head_show"`
	Daka           int    `json:"daka"`
	FlagNumber     int    `json:"flag_number"`
	Count          int    `json:"count"`
	MonthLearnTime int    `json:"month_learn_time"`
	Token          string `json:"token"`
}

type LoginWithOTPReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Message string `json:"message"`
}

type SearchUserReq struct {
	Keyword string `json:"keyword"`
}

type SearchUserResp struct {
	Users []UserInfoResp `json:"users"`
}

type SendEmailCodeReq struct {
	Email string `json:"email"`
}

type SendEmailCodeResp struct {
	Message string `json:"message"`
}

type SwitchHeadReq struct {
	Number int `json:"number"`
}

type TodayPointsResp struct {
	TodayPoints int `json:"today_points"`
}

type UpdatePasswordReq struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type UpdatePasswordResp struct {
	Success  bool   `json:"success"`
	NewToken string `json:"new_token"`
}

type UpdateRemindTimeReq struct {
	TimeRemind int `json:"time_remind"`
	MinRemind  int `json:"min_remind"`
}

type UpdateStatusReq struct {
	Status string `json:"status"`
}

type UpdateUsernameReq struct {
	NewName string `json:"new_name"`
}

type UserInfoResp struct {
	Id             uint   `json:"id"`
	UserId         uint   `json:"user_id"`
	Username       string `json:"username"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	HeadShow       int    `json:"head_show"`
	Daka           int    `json:"daka"`
	FlagNumber     int    `json:"flag_number"`
	Count          int    `json:"count"`
	MonthLearnTime int    `json:"month_learn_time"`
}

type UserStatsReq struct {
	UserId uint `form:"user_id,optional"`
}

type UserStatsResp struct {
	UserId         uint   `json:"user_id"`
	Name           string `json:"name"`
	HeadShow       int    `json:"head_show"`
	AvatarIndex    int    `json:"avatar_index"`
	TotalPoints    int    `json:"total_points"`
	MonthLearnTime int    `json:"month_learn_time"`
	CompletedFlags int    `json:"completed_flags"`
	FlagNumber     int    `json:"flag_number"`
	DakaDays       int    `json:"daka_days"`
}

type VerifyEmailReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type VerifyEmailResp struct {
	Success bool `json:"success"`
}
